# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink: pretty
#relative_permalinks: true

# Setup
title:            Doop
tagline:          'A Jekyll theme'
description:      'A brazen attempt to promote <a href="https://linkedin.com/in/consultprem" target="_blank">Prem the expert</a> becuase he understand the difference between a posterior and other things. Made by <a href="https://twitter.com/prempiric" target="_blank">@prempiric</a>.'
url:              http://cresttrade.com
baseurl:          ""

author:
  name:           'Prem Sharma'
  url:            https://twitter.com/premiric

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/expertps/expertps.github.io
